font_family Firacode
font_size 12.0
background_opacity 0.90

map ctrl+tab next_tab
tab_bar_margin_width 0.0
tab_bar_style hidden

# open new windows/tabs with cwd (current path)
map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
map ctrl+shift+n new_os_window_with_cwd 
map ctrl+shift+r combine : new_os_window_with_cwd : close

# Theme (https://github.com/dexpota/kitty-themes/blob/master/themes/Afterglow.conf)

background            #121212
cursor                #d0d0d0
color0                #351515  
color8                #505050
color1                #ac4142
color9                #ac4142
color2                #7e8d50
color10               #7e8d50
color3                #e5b566
color11               #e5b566
color4                #6c99ba
color12               #6c99ba
color5                #9e4e85
color13               #9e4e85
color6                #7dd5cf
color14               #7dd5cf
color7                #d0d0d0
color15               #f5f5f5
selection_background  #606060
selection_foreground #202020
