{config, pkgs, ...}:
let 
  config_dir = "~/conf";

    tmux_repl_conf = builtins.path {path=./editor/tmux-repl.conf; name="tmux-repl";};

    vimrc = pkgs.writeText "vimrc" (builtins.readFile ./editor/vimrc +
    ''

    " generated by nix ! 
    let g:startify_bookmarks = [{'c':'${config_dir}/editor'}]

    command TmuxReplStart call system('tmux -f ${tmux_repl_conf} start-server') | echo 'join session with `tmux a`'
    command TmuxReplKil call system('tmux kill-session -t repl')

    map Z !!tee -a /tmp/tmux-repl<cr>
    ''
    );

in {
  home.username = "rambi";
  home.homeDirectory = "/home/rambi";

  home.stateVersion = "21.05";

  home.packages = with pkgs; let
    dev_tools = [
      tldr
      macchina
      llvmPackages_12.llvm
      rust-analyzer
      rustup
      crate2nix
      yarn
      wabt
      any-nix-shell
      (import ./tools/idris2-pkgs).default
      (import ./tools/idris2-pkgs).packages.x86_64-linux.lsp
      busybox
    ];
    desktop_tools = [
      i3status-rust
      dunst
      vimPlugins.Vundle-vim
      bat
      # TODO: picom ?
      #python38Packages.Wand
      (import ./desktop/scripts.nix {inherit pkgs;})
    ];

  in dev_tools ++ desktop_tools;

  programs.fish = {
    enable = true;
    interactiveShellInit = ''
    set fish_greeting
    fish_vi_key_bindings
    alias v=nvim
    alias c=clear
    macchina
    '';
    promptInit = ''
    any-nix-shell fish --info-right | source
    '';
  };

  programs.tmux = {
    enable = true;
    shell = "${pkgs.fish}/bin/fish";
  };


  xdg.userDirs = {
    download = "\$HOME/Downloads";
    desktop = "\$HOME";
    pictures = "\$HOME/Pictures";
  };

  xsession.windowManager.xmonad = {
    enable = true;
    config = ./desktop/xmonad.hs;
    enableContribAndExtras = true;
  };

  xdg.configFile = {
    "macchina/macchina.toml"   .source = 
    let first_line = "custom_ascii = '${builtins.path {path=./ascii/arco; name="ascii";}}'\n";
    in pkgs.writeText "macchina-conf" (first_line + (builtins.readFile ./other/macchina));

    "kitty/kitty.conf"         .source = ./desktop/kitty.conf;
    "i3status-rust/config.toml".source = ./desktop/i3status-rust;
    "i3/config"                .source = ./desktop/i3;
    "picom/picom.conf"         .source = ./desktop/picom.conf;
    "nvim/init.lua"            .source = ./editor/nvim.lua;
  };

  home.file = { 
    ".vimrc"  .source = vimrc;
  };
}
