{config, pkgs, ...}:
let custom_xinitrc = pkgs.stdenv.mkDerivation {
    # my custom layout: create a binary file layout.xkm
      # from a layout (./xorg/beprog) and a description file (./xorg/config.xkb)
      name = "my_xinit_with_beprog";
      src = ./desktop;
      buildInputs = [pkgs.xorg.xkbcomp];
      buildPhase = ''
        mkdir symbols
        cp beprog symbols/
        xkbcomp -w 0 -I./ -xkm -o layout.xkm - << EOF
        xkb_keymap {
          xkb_keycodes  { include "evdev+aliases(qwerty)" };
          xkb_types     { include "complete"  };
          xkb_compat    { include "complete"  };
          xkb_symbols   { include "pc+beprog+fr:2+terminate(ctrl_alt_bksp)"  };
          xkb_geometry  { include "pc(pc104)" };
        };
        EOF

        echo "setxkbmap typo,fr" > xinitrc
        echo "xkbcomp -w 0 $out/layout.xkm \$DISPLAY" >> xinitrc
        echo "exec i3" >> xinitrc
      '';
      installPhase = ''
        mkdir $out
        mv xinitrc $out
        mv layout.xkm $out
      '';
    };

    tmux_repl_conf = builtins.path {path=./editor/tmux-repl.conf; name="tmux-repl";};

    vimrc = pkgs.writeText "vimrc" (builtins.readFile ./editor/vimrc +
    ''

    " generated by nix ! 
    let g:startify_bookmarks = [{'c':'~/conf/editor'}]

    command TmuxReplStart call system('tmux -f ${tmux_repl_conf} start-server') | echo 'join session with `tmux a`'
    command TmuxReplKil call system('tmux kill-session -t repl')

    map Z !!tee -a /tmp/tmux-repl<cr>
    ''
    );

in {
  home.username = "rambi";
  home.homeDirectory = "/home/rambi";

  home.stateVersion = "21.05";

  home.packages = with pkgs; let
    dev_tools = [
      tldr
      macchina
      llvmPackages_12.llvm
      rust-analyzer
      rustup
      crate2nix
      wabt
    ];
    desktop_tools = [
      i3status-rust
      kbdd
      dunst
      vimPlugins.Vundle-vim
      bat
      # TODO: picom ?
      #python38Packages.Wand
    ];
  in dev_tools ++ desktop_tools;

  programs.fish = {
    enable = true;
    interactiveShellInit = ''
    set fish_greeting
    fish_vi_key_bindings
    alias v=nvim
    macchina
    '';
  };

  programs.tmux = {
    enable = true;
    shell = "${pkgs.fish}/bin/fish";
  };


  xdg.userDirs = {
    download = "\$HOME/Downloads";
    desktop = "\$HOME";
    pictures = "\$HOME/Pictures";
  };

  xdg.configFile = {
    "macchina/macchina.toml"   .source = 
    let first_line = "custom_ascii = '${builtins.path {path=./ascii/arco; name="ascii";}}'\n";
    in pkgs.writeText "macchina-conf" (first_line + (builtins.readFile ./other/macchina));

    "kitty/kitty.conf"         .source = ./desktop/kitty.conf;
    "i3status-rust/config.toml".source = ./desktop/i3status-rust;
    # FIXME: files to directory ?
    "i3/config"                .source = ./desktop/i3;
    "i3/scripts"               .source = ./desktop/scripts;
    "picom/picom.conf"         .source = ./desktop/picom.conf;
    "nvim/init.lua"            .source = ./editor/nvim.lua;
  };

  home.file = { 
    ".vimrc"  .source = vimrc;
    ".xinitrc".source = custom_xinitrc + "/xinitrc";
  };
}
