# to use this file, create tmux server with `tmux -f .tmux-repl.conf start-server`
new-session -d -s repl sh

# create new temporary file (like a log file)
run "true > /tmp/tmux-repl"
# and tail it to the pane (any new content is send to the active shell)
pipe-pane -I 'tail -f /tmp/tmux-repl'

# to join, use `tmux attach -t repl`
# it will ask you for an interpreter for the repl (python, ghci ...) none is shell
# FIXME
# set-hook -g client-attached 'command-prompt -p "Interpreter: " "send exec SPACE %1 ENTER C-l"' 
