#!/bin/python3

from os import environ, listdir
from subprocess import Popen, PIPE, call
import random
from wand.image import Image

folder = environ['HOME']+'/Wallpapers/'
choice = folder+random.choice(listdir(folder))

# sample image to get average color (imageMagick)
sampler = Popen(["convert", choice, "-resize", "1x1", "-format", "%[fx:int(255*r+.3)] %[fx:int(255*g+.3)] %[fx:int(255*b+.3)]", "info:-"], stdout=PIPE)

# set image to bg
call(['feh', '--bg-fill', choice])

# set Xressource option "bg" to the average color

with Image(filename=choice) as img:
    img.sample(5, 5)
    img.sample(1, 1)

    pix = img[0][0]
    r, g, b = [min(150, col) for col in (pix.red_int8, pix.green_int8, pix.blue_int8)]
    print(r, g, b)

p = Popen('xrdb', stdin=PIPE)

report = \
f"""
*bg: #{r:02x}{g:02x}{b:02x}
*bg_opposite: #{256-r:02x}{256-g:02x}{256-b:02x}
"""

p.communicate(report.encode())

with open('/tmp/current_wallpaper', 'w') as f:
    f.write(choice)
